Add MultiValueArithmeticDriver<T> Component
Xlinka/NeosPlus pull request #146
Opened 2023-07-25 15:00 UTC by Nytra

It's basically a small calculator in components. You can add, subtract, multiply or divide with it. You can also type values straight into the component or drive them from elsewhere.

![20230725153324_1](https://github.com/Xlinka/NeosPlus/assets/14206961/95534ca8-8f50-4f12-9b8e-665da52ead49)

2023-07-25 15:24 UTC, Nytra commented
Not sure why the check is failing :/

2023-07-25 18:53 UTC, Xlinka commented
OH yeah the github action script has been broken for a long time

2023-07-25 18:53 UTC, Xlinka commented
https://github.com/Xlinka/NeosPlus/issues/138

2023-07-30 17:40 UTC, Xlinka commented
has this been fully tested in a multi user enviroment

2023-07-30 20:38 UTC, Nytra commented
> has this been fully tested in a multi user enviroment

No not yet.

2023-08-06 15:41 UTC, Xlinka commented
when do you want to test ?

2023-08-08 05:48 UTC, Nytra commented
sorry I have been busy with stuff so haven't been able to test, but hopefully soon

2023-08-08 06:56 UTC, Frozenreflex requested changes
This PR looks alright, better than most other people's code I've had to read. There's a couple small changes here and there that I'd like to see

2023-08-08 06:56 UTC, Frozenreflex commented on NEOSPlus/Components/Transform/Drivers/MultiValueArithmeticDriver.cs
> +
There needs to be a namespace defined here,
```cs
namespace FrooxEngine;
```
should do.

(Linka please fix the namespaces in your code it's missing in a couple of places and dropping stuff to the global namespace is bad)

2023-08-08 06:56 UTC, Frozenreflex commented on NEOSPlus/Components/Transform/Drivers/MultiValueArithmeticDriver.cs
> +        if (!Target.IsLinkValid)
This could probably be reformatted to something like this
```cs
if (!Target.IsLinkValid || Values.Count == 0) return;
```

2023-08-08 06:57 UTC, Frozenreflex commented on NEOSPlus/Components/Transform/Drivers/MultiValueArithmeticDriver.cs
> +            // don't let the component drive itself, don't want a feedback loop
Good catch.

2023-08-09 05:42 UTC, Frozenreflex approved these changes

2023-09-05 10:03 UTC, Xlinka commented
approved

2023-09-05 10:03 UTC, merged