Nearest User Node
Xlinka/NeosPlus pull request #63
Opened 2022-08-25 16:08 UTC by LeCloutPanda

Nearest user node

For issues [57](https://github.com/Xlinka/NeosPlus/issues/57) and [39](https://github.com/Xlinka/NeosPlus/issues/39)

2022-08-25 16:30 UTC, Xlinka commented
Use More Appropriate Names when doing pull requests and what the node is in the title and not use "Deez"

2022-08-25 16:31 UTC, LeCloutPanda commented
Sorry :)

2022-08-25 23:06 UTC, Frozenreflex requested changes

2022-08-25 23:06 UTC, Frozenreflex commented on NEOSPlus.csproj
> +    <Compile Include="Logix\Slots\FindAllChildrenWithTag.cs" />
Remove these two

2022-08-26 05:40 UTC, LeCloutPanda commented on NEOSPlus.csproj
> +    <Compile Include="Logix\Slots\FindAllChildrenWithTag.cs" />
Should be gone now.

2022-08-27 17:22 UTC, Frozenreflex approved these changes

2022-08-30 12:16 UTC, merged